### PR TITLE
v1.0.5 Update with the latest fixes

### PR DESCRIPTION
**Pull request by pioneerit**
@jmauro here is the PR for bumping the version
And attempt to fix Travis CI builds

### CODE REVIEW

**Comment by jmauro** [comment]
All good now 😉

**Comment by pioneerit** [comment]
```#docker run -v $(pwd):/knife johnbarney/docker-knife:latest supermarket show etckeeper
average_rating:
category:        Utilities
created_at:      2013-03-22T07:22:05.000Z
deprecated:      false
description:     Installs/Configures etckeeper
external_url:    https://github.com/pioneerit/etckeeper-cookbook
issues_url:      https://github.com/pioneerit/etckeeper-cookbook/issues
latest_version:  https://supermarket.chef.io/api/v1/cookbooks/etckeeper/versions/1.0.5
metrics:
  downloads:
    total:    6516046
    versions:
      0.0.2: 1208604
      0.0.3: 1208581
      1.0.1: 1208573
      1.0.2: 1208603
      1.0.3: 916412
      1.0.4: 765273
      1.0.5: 0
name:            etckeeper
source_url:      https://github.com/pioneerit/etckeeper-cookbook
updated_at:      2022-04-27T17:01:34.721Z
...
```

Thanks @jmauro for all the help,
I could reset the keys and make it work to upload the new version.

**Comment by jmauro** [comment]
Hello,

Not sure to follow what you are asking to do.

Kind regards,
JM

**Comment by pioneerit** [comment]
Nothing, just give an update that new version with you fixes are available now in https://supermarket.chef.io/cookbooks/etckeeper

**Comment by jmauro** [comment]
Cool thx.

I might push other updates. Let me know if it is too much.

Kind Regards,
JM

**Comment by pioneerit** [comment]
No problems, old Travis is fixed, so it is even easier now.

**Pull request merged**
